# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('img', 'img'),
    ],
    hiddenimports=[
        'dearpygui.dearpygui',
        'pymem',
        'pymem.process',
        'pymem.exception',
        'pypresence',
        'serial',
        'serial.tools.list_ports',
        'pyMeow',
        'win32api',
        'win32gui',
        'win32con',
        'win32process',
        'keyboard',
        'ctypes',
        'threading',
        'multiprocessing',
        'requests',
        'hashlib',
        'shutil',
        'json',
        'struct',
        'logging',
        'time',
        'math',
        'os',
        'GUI.gui_mainloop',
        'GUI.gui_util',
        'ext.datatypes',
        'ext.offsets',
        'features.aimbot',
        'features.bhop',
        'features.bombtimer',
        'features.combined',
        'features.discodrpc',
        'features.esp',
        'features.fovchanger',
        'features.rcs',
        'functions.autoupdate',
        'functions.calculations',
        'functions.gameinput',
        'functions.memfuncs',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='cs2py',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='cs2py',
)
